import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: React.FC = (): JSX.Element => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mainContainer'>

      </main>

    </div>
  )
}

export default Home
